- name: default value
  hosts: localhost
  tasks:
  - name: print default value
    ansible.builtin.debug:
      msg: "hello {{course | default('ansible')}} "

- name: upper case
  hosts: localhost
  vars:
    greeting: "hello good morning"
  tasks:
  - name: convert into uppercase
    ansible.builtin.debug:
      msg: "{{ greeting | upper}}"

- name: lower case
  hosts: localhost
  vars:
    greeting: "hello good morning"
  tasks:
  - name: convert into lowercase
    ansible.builtin.debug:
      msg: "{{ greeting | lower}}"

- name: remove duplicates
  hosts: localhost
  vars:
    numbers: [3, 6, 9, 9, 6, 11, 50, 50, 6, 3]
  tasks:
  - name: remove duplicates
    ansible.builtin.debug:
      msg: "{{ numbers | unique}}"

- name: print min and max
  hosts: localhost
  vars:
    ages: [26, 40, 60, 68]
  tasks:
  - name: print min and max
    ansible.builtin.debug:
      msg: "min age: {{ ages | min}}, max age: {{ ages | max}}"

- name: convert dictionary into items/list
  host: localhost
  vars:
    my_dict:  # this is called as dictionary or map or key/value pairs
      Course: Ansible
      Trainer: Shiva kumar
      Duration: 120hrs
  tasks:
  - name: before convert
    ansible.builtin.debug:
      msg: "Before convert: {{ my_dict }}"
  - name: After convert
    ansible.builtin.debug:
      msg: "After convert: {{ my_dict | dict2items}}"