- name: variables
  hosts: localhost
  vars: #variable declation
    course: "Terraform"
    trainer: "Siva"
    duration: "150hrs"
  tasks:
  - name: print override information
    vars: #variable declation
      course: "DevOps"
    ansible.builtin.debug:
      msg: "hi, we are learning {{course}} from trainer {{trainer}}, duration is {{duration}}."
  
  - name: print information
    ansible.builtin.debug:
      msg: "hi, we are learning {{course}} from trainer {{trainer}}, duration is {{duration}}."