- name: variables from inventory
  hosts: localhost
  tasks:
  - name: print information
    vars:
      timings: "07:15AM IST "
    ansible.builtin.debug:
      msg: "hi, we are learning {{Course}} from Trainer {{Trainer}}, Duration {{Duration}}."
      Timings are: "{{Timings}}"